---
- name: devmachine_provisioner
  hosts: devmachines
  become: true
  tasks:
    - name: Install pacman tools
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - kate
        - keepass
        - libreoffice
        - minikube
        - kubectl
        - docker 
        - podman
        - archlinux-keyring
        - qemu 
        - virt-manager 
        - virt-viewer 
        - dnsmasq 
        - vde2 
        - bridge-utils 
        - gnu-netcat
        - rustup
        - istio
        - virtualbox
    - name: Create opt folder for apps
      file: 
        path: /opt/jetbrains
        state: directory
        mode: 0777
    - name: Install jetbrains toolbox 
      ansible.builtin.unarchive:
        src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.25.12627.tar.gz
        dest: /opt/jetbrains
        remote_src: yes
    - name: Install rust 
      shell: rustup install stable
      become_user: phiro